version: '3.8'

services:
  ecommerce-api:
    build:
      context: .
      dockerfile: ./Ecommerce.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ecommerce-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DatabaseConnection=Host=ecommerce-db;Port=5432;Database=ecommerce_demo;Username=postgres;Password=postgres
    networks:
      - app-network

  ecommerce-db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: ecommerce_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  app-network:
